Update Dockerfile and Workflows

diff --git a/.github/workflows/build-test.yml b/.github/workflows/build-test.yml
--- a/.github/workflows/build-test.yml
+++ b/.github/workflows/build-test.yml
@@ -29,14 +29,20 @@ jobs:
         # We use .go-version as our source of truth for current Go
         # version, because "goenv" can react to it automatically.
         run: |
-          if [[ ! -f .go-version ]] ; then echo "::error::File not found: .go-version" && exit 1; fi
+          if [[ ! -f .go-version ]] ; then
+            echo "::error::File not found: .go-version"
+            exit 1
+          fi
           echo "Building with Go $(cat .go-version)"
           echo "::set-output name=go_version::$(cat .go-version)"
       - name: get product version
         id: get_product_version
         run: |
           make version
-          if [[ $? -ne 0 ]] ; then echo "::error::make version exited with non-zero exit code." && exit 1; fi
+          if [[ $? -ne 0 ]] ; then
+            echo "::error::make version exited with non-zero exit code."
+            exit 1
+          fi
           echo "::set-output name=product_version::$(make version)"
       - name: get repo name without owner
         id: get_repo_name
@@ -107,7 +113,6 @@ jobs:
           path: out/${{ env.RPM_PACKAGE }}
 
       - uses: actions/upload-artifact@v2
-        if: ${{ matrix.goos == 'linux' }}
         with:
           name: ${{ env.DEB_PACKAGE }}
           path: out/${{ env.DEB_PACKAGE }}
@@ -127,11 +132,9 @@ jobs:
         uses: hashicorp/actions-docker-build@v1
 
         with:
-          # Add smoke test here. Below is a sample smoke test that runs the built image
-          # and validates the version.
           smoke_test: |
-            TEST_VERSION="$(docker run "${IMAGE_NAME}" | awk '/CLI version/{print $3}')"
-            if [ "${TEST_VERSION}" != "${version}" ]; then
+            TEST_VERSION="$(docker run "${IMAGE_NAME}" | awk '/Nomad Pack/{print $3}')"
+            if [ "${TEST_VERSION#v}" != "${version}" ]; then
               echo "Test FAILED"
               exit 1
             fi
@@ -142,25 +145,6 @@ jobs:
           tags: |
             docker.io/hashicorp/${{needs.get_build_info.outputs.repo_name}}:${{needs.get_build_info.outputs.product_version}}
             986891699432.dkr.ecr.us-east-1.amazonaws.com/hashicorp/${{needs.get_build_info.outputs.repo_name}}:${{needs.get_build_info.outputs.product_version}}
-          # dev_tags are tags that get automatically pushed whenever successful
-          # builds make it to the stable channel. The intention is for these tags
-          # to be used for early testing of new code prior to official releases
-          # going out. The stable channel implies that all tests and scans have
-          # completed successfully, so these images should be _stable_ but are not
-          # intended for production use.
-          #
-          # Here we have two example dev tags. The first (ending -dev) is a tag
-          # that will be updated over-and-over as new builds arrive in stable.
-          #
-          # The second (using the git SHA) will produce a new separate tag for
-          # each commit that is built. (These can still be overridden if the same
-          # commit is built successfully a second time, but that is a less likely
-          # scenario.) These kinds of dev tags are useful if you want to be able
-          # to use Docker images built from those specific commits.
-          #
-          # NOTE: dev_tags MUST publish to the 'hashicorppreview' DockerHub org, it
-          # will fail to any other DockerHub org or registry. You can optionally
-          # prepend docker.io
           dev_tags: |
             ${{ format('hashicorppreview/{0}:{1}-dev', needs.get_build_info.outputs.repo_name, needs.get_build_info.outputs.product_version) }}
             ${{ format('docker.io/hashicorppreview/{0}:{1}-{2}', needs.get_build_info.outputs.repo_name, needs.get_build_info.outputs.product_version, github.sha) }}
diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,15 +1,8 @@
 name: build
 
-# We now default to running this workflow on every push to every branch.
-# This provides fast feedback when build issues occur, so they can be
-# fixed prior to being merged to the main branch.
-#
-# If you want to opt out of this, and only run the build on certain branches
-# please refer to the documentation on branch filtering here:
-#
-#   https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushbranchestagsbranches-ignoretags-ignore
-#
-on: [workflow_dispatch, push]
+on:
+  - workflow_dispatch
+  - push
 
 env:
   PKG_NAME: "nomad-pack"
@@ -27,7 +20,10 @@ jobs:
         # We use .go-version as our source of truth for current Go
         # version, because "goenv" can react to it automatically.
         run: |
-          if [[ ! -f .go-version ]] ; then echo "::error::File not found: .go-version" && exit 1; fi
+          if [[ ! -f .go-version ]]; then
+            echo "::error::File not found: .go-version"
+            exit 1
+          fi
           echo "Building with Go $(cat .go-version)"
           echo "::set-output name=go-version::$(cat .go-version)"
 
@@ -71,15 +67,17 @@ jobs:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        goos: [freebsd, windows, netbsd, openbsd, solaris]
-        goarch: ["386", "amd64", "arm"]
+        goos:
+          - "freebsd"
+          - "windows"
+        goarch:
+          - "386"
+          - "amd64"
+          - "arm"
+          - "arm64"
         exclude:
-          - goos: solaris
-            goarch: 386
-          - goos: solaris
-            goarch: arm
-          - goos: windows
-            goarch: arm
+          - goos: "windows"
+            goarch: "arm"
 
       fail-fast: true
 
@@ -114,7 +112,7 @@ jobs:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        goos: [linux]
+        goos: ["linux"]
         goarch: ["arm", "arm64", "386", "amd64"]
 
       fail-fast: true
@@ -147,16 +145,16 @@ jobs:
         if: ${{ matrix.goos == 'linux' }}
         uses: hashicorp/actions-packaging-linux@v1
         with:
-          name: ${{ github.event.repository.name }}
-          description: "crt-core-helloworld is a template repo for oss products."
+          name: "nomad-pack"
+          description: "nomad-pack is a job specification packaging engine for HashiCorp Nomad."
           arch: ${{ matrix.goarch }}
           version: ${{ needs.get-product-version.outputs.product-version }}
           maintainer: "HashiCorp"
-          homepage: "https://github.com/hashicorp/crt-core-helloworld"
+          homepage: "https://github.com/hashicorp/nomad-pack"
           license: "MPL-2.0"
           binary: "dist/${{ env.PKG_NAME }}"
-          deb_depends: "openssl"
-          rpm_depends: "openssl"
+          deb_depends: "openssl,git"
+          rpm_depends: "openssl,git"
 
       - name: Set Package Names
         if: ${{ matrix.goos == 'linux' }}
@@ -233,8 +231,8 @@ jobs:
           # Add smoke test here. Below is a sample smoke test that runs the built image
           # and validates the version.
           smoke_test: |
-            TEST_VERSION="$(docker run "${IMAGE_NAME}" | awk '/CLI version/{print $3}')"
-            if [ "${TEST_VERSION}" != "${version}" ]; then
+            TEST_VERSION="$(docker run "${IMAGE_NAME}" version | awk '/Nomad Pack/{print $3}')"
+            if [ "${TEST_VERSION#v}" != "${version}" ]; then
               echo "Test FAILED"
               exit 1
             fi
@@ -245,68 +243,11 @@ jobs:
           tags: |
             docker.io/hashicorp/${{ env.repo }}:${{ env.version }}
             986891699432.dkr.ecr.us-east-1.amazonaws.com/hashicorp/${{ env.repo }}:${{ env.version }}
-          # dev_tags are tags that get automatically pushed whenever successful
-          # builds make it to the stable channel. The intention is for these tags
-          # to be used for early testing of new code prior to official releases
-          # going out. The stable channel implies that all tests and scans have
-          # completed successfully, so these images should be _stable_ but are not
-          # intended for production use.
-          #
-          # Here we have two example dev tags. The first (ending -dev) is a tag
-          # that will be updated over-and-over as new builds arrive in stable.
-          #
-          # The second (using the git SHA) will produce a new separate tag for
-          # each commit that is built. (These can still be overridden if the same
-          # commit is built successfully a second time, but that is a less likely
-          # scenario.) These kinds of dev tags are useful if you want to be able
-          # to use Docker images built from those specific commits.
-          #
-          # NOTE: dev_tags MUST publish to the 'hashicorppreview' DockerHub org, it
-          # will fail to any other DockerHub org or registry. You can optionally
-          # prepend docker.io
+
           dev_tags: |
             hashicorppreview/${{ env.repo }}:${{ env.version }}-dev
             docker.io/hashicorppreview/${{ env.repo }}:${{ env.version }}-${{ github.sha }}
 
-  build-docker-alternate:
-    name: Docker ${{ matrix.arch }} alternate release build
-    needs:
-      - get-product-version
-      - build-linux
-    runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        arch: ["arm", "arm64", "386", "amd64"]
-    env:
-      repo: ${{ github.event.repository.name }}
-      version: ${{ needs.get-product-version.outputs.product-version }}
-
-    steps:
-      - uses: actions/checkout@v2
-      - uses: hashicorp/actions-docker-build@v1
-        with:
-          version: ${{ env.version }}
-          target: release-alternate
-          arch: ${{ matrix.arch }}
-          tags: |
-            docker.io/hashicorp/${{ env.repo }}-alternate:${{ env.version }}
-            986891699432.dkr.ecr.us-east-1.amazonaws.com/hashicorp/${{ env.repo }}-alternate:${{ env.version }}
-          dev_tags: |
-            hashicorppreview/${{ env.repo }}-alternate:${{ env.version }}-dev
-            docker.io/hashicorppreview/${{ env.repo }}-alternate:${{ env.version }}-${{ github.sha }}
-
-  # build-docker-redhat is an example of how to build a Red Hat Certified Container (RHCC) Image.
-  # This means it uses the 'redhat_tag' input, instead of 'tags' and 'dev_tags'.
-  #
-  # It's important to note that there are other important differences with RHCC images, compared
-  # with calls using the 'tags' and optionally 'dev_tags' inputs:
-  #
-  #   - They can only be built for a single architecture,
-  #     so the 'arch' input is hard-coded to 'amd64' in this case.
-  #   - Therefore, we don't use a matrix to expand over architectures,
-  #     when using the 'redhat_tag' input.
-  #   - We can only specify a single 'redhat_tag' not multiple tags,
-  #     as with the 'tags' and 'dev_tags' inputs.
   build-docker-redhat:
     name: Docker ${{ matrix.arch }} alternate release build
     needs:
